"""Robust Data Ingestion & Validation Pipeline for HAKIKI-KPC Phase 1.

Idempotent, production-ready pipeline that:
  1. Loads raw data from SQLite (generated by generate_custody_data.py)
  2. Enforces schema & type validation
  3. Calculates custody reconciliation discrepancies
  4. Outputs validated Parquet + SQLite ready for ML feature engineering
"""

from __future__ import annotations

import sqlite3
from datetime import datetime
from typing import Dict, Any

import numpy as np
import pandas as pd


# ---------------------------------------------------------------------------
# Schema Enforcement & Type Validation
# ---------------------------------------------------------------------------

REQUIRED_SCHEMA: Dict[str, Dict[str, Any]] = {
    "kra_manifests": {
        "columns": {
            "manifest_id": str,
            "omc": str,
            "product_type": str,
            "declared_volume_litres": float,
            "source": str,
            "destination_type": str,
            "bond_status": str,
            "timestamp": str,
        },
        "valid_values": {
            "product_type": ["PMS", "AGO", "DPK"],
            "destination_type": ["Domestic", "Transit EAC"],
            "bond_status": ["Active", "Pending", "Discharged"],
        },
    },
    "rects_telemetry": {
        "columns": {
            "consignment_id": str,
            "vehicle_seal_id": str,
            "timestamp": str,
            "gps_latitude": float,
            "gps_longitude": float,
            "geofence_status": str,
            "e_seal_tamper_flag": int,
            "dwell_time_minutes": int,
        },
        "valid_values": {
            "geofence_status": ["OK", "Out-of-Corridor", "Route-Deviation"],
            "e_seal_tamper_flag": [0, 1],
        },
    },
    "kpc_depot_meters": {
        "columns": {
            "meter_transaction_id": str,
            "consignment_id": str,
            "depot_id": str,
            "meter_in_volume": float,
            "meter_out_volume": float,
            "temperature": float,
            "observed_density_kg_per_m3": float,
        },
    },
    "depot_lab_quality": {
        "columns": {
            "lab_test_id": str,
            "consignment_id": str,
            "depot_id": str,
            "sample_timestamp": str,
            "density_at_15c": float,
            "research_octane_number": int,
            "flash_point": float,
            "sulfur_content_ppm": float,
            "pass_quality_flag": int,
        },
        "valid_values": {
            "pass_quality_flag": [0, 1],
        },
    },
    "reconciled_custody_events": {
        "columns": {
            "event_id": str,
            "manifest_id": str,
            "consignment_id": str,
            "depot_id": str,
            "volumetric_shrinkage_pct": float,
            "density_deviation_pct": float,
            "custody_handover_anomaly_index": float,
            "anomaly_risk_flag": str,
            "calculated_at": str,
        },
        "valid_values": {
            "anomaly_risk_flag": ["Low", "Medium", "High"],
        },
    },
}


def validate_column_types(df: pd.DataFrame, schema: Dict[str, Any]) -> pd.DataFrame:
    """Validate and coerce column types per schema. Raises ValueError on failure."""
    for col, dtype in schema["columns"].items():
        if col not in df.columns:
            raise ValueError(f"Missing required column: {col}")
        try:
            df[col] = df[col].astype(dtype)
        except (ValueError, TypeError) as e:
            raise ValueError(f"Type coercion failed for column {col}: {e}")

    # Validate enumerated columns
    for val_col, allowed in schema.get("valid_values", {}).items():
        if val_col in df.columns:
            for idx, val in df[val_col].items():
                if val not in allowed:
                    raise ValueError(
                        f"Invalid value '{val}' in column '{val_col}' at index {idx}. "
                        f"Allowed: {allowed}"
                    )

    return df


# ---------------------------------------------------------------------------
# Custody Reconciliation & Discrepancy Engine
# ---------------------------------------------------------------------------

def compute_volumetric_shrinkage(df: pd.DataFrame) -> pd.Series:
    """Volumetric Shrinkage (%) = (V_manifest - V_depot_meter) / V_manifest * 100."""
    manifest_vol = df["declared_volume_litres"]
    depot_vol = df["meter_in_volume"]
    # Avoid division by zero
    with np.errstate(divide="ignore", invalid="ignore"):
        shrinkage = ((manifest_vol - depot_vol) / manifest_vol) * 100
    shrinkage = shrinkage.replace([np.inf, -np.inf], np.nan).fillna(0)
    return shrinkage.round(2)


def compute_density_deviation(df: pd.DataFrame) -> pd.Series:
    """Density Deviation (%) = |ρ_lab - ρ_declared| / ρ_declared * 100."""
    rho_lab = df["density_at_15c"]
    rho_dec = df["declared_density_kg_per_m3"]
    with np.errstate(divide="ignore", invalid="ignore"):
        dev = (np.abs(rho_lab - rho_dec) / rho_dec) * 100
    dev = dev.replace([np.inf, -np.inf], np.nan).fillna(0)
    return dev.round(2)


def compute_anomaly_index(
    seal_tamper: np.ndarray,
    geofence: np.ndarray,
    density_dev: np.ndarray,
) -> np.ndarray:
    """Custody Handover Anomaly Index combining seal tamper, route deviation, and quality variance.

    Weights: seal tamper 0.4 + geofence deviation 0.4 + density variance 0.2
    Geofence mapping: OK=0, Out-of-Corridor=1, Route-Deviation=2
    Output scaled to 0–100.
    """
    # Encode geofence
    geofence_enc = np.where(geofence == "Route-Deviation", 2,
                            np.where(geofence == "Out-of-Corridor", 1, 0)).astype(float)

    # Normalize density deviation (clamp extreme values)
    dev_norm = np.clip(density_dev / np.percentile(density_dev[density_dev > 0], 95), 0, 1)

    # Weighted composite
    raw = 0.4 * seal_tamper.astype(float) + 0.4 * geofence_enc + 0.2 * dev_norm
    # Scale to 0–100
    index = np.clip(raw * 100, 0, 100)
    return np.round(index, 2)


def assign_risk_flag(
    anomaly_index: np.ndarray,
    seal_tamper: np.ndarray,
    density_dev: np.ndarray,
    quality_flag: np.ndarray,
) -> np.ndarray:
    """Assign anomaly risk flag: Low / Medium / High."""

    # Base thresholds on anomaly index
    high_thresh = 70.0
    med_thresh = 40.0

    risk = np.where(anomaly_index >= high_thresh, "High",
                    np.where(anomaly_index >= med_thresh, "Medium", "Low"))

    # Quality failure bump: if pass_quality_flag == 0, ensure at least Medium
    quality_failure = quality_flag == 0
    risk = np.where(
        quality_failure & (risk == "Low"), "Medium", risk
    )

    # Dampen High if density normal (no density deviation)
    normal_density = density_dev < 5.0
    risk = np.where(
        normal_density & (risk == "High"), "Medium", risk
    )

    return risk


# ---------------------------------------------------------------------------
# Pipeline: Load → Validate → Reconcile → Output
# ---------------------------------------------------------------------------

class CustodyIngestionPipeline:
    """Production-ready ingestion pipeline for HAKIKI-KPC custody data."""

    def __init__(self, db_path: str = "/home/mike_mitch/Desktop/EMTech/final_capstone/data/custody_data.db"):
        self.db_path = db_path
        self.conn: sqlite3.Connection | None = None
        self.dfs: Dict[str, pd.DataFrame] = {}

    def load_raw_data(self) -> None:
        """Load all tables from the source SQLite database."""
        self.conn = sqlite3.connect(self.db_path)
        tables = ["kra_manifests", "rects_telemetry", "kpc_depot_meters", "depot_lab_quality"]

        for table in tables:
            df = pd.read_sql(f"SELECT * FROM {table}", self.conn)
            # Ensure timestamp columns are parsed
            if "timestamp" in df.columns:
                df["timestamp"] = pd.to_datetime(df["timestamp"], errors="coerce")
            self.dfs[table] = df

        # Load reconciled if exists
        if "reconciled_custody_events" in pd.read_sql(
            "SELECT name FROM sqlite_master WHERE type='table'", self.conn
        ).name:
            self.dfs["reconciled_custody_events"] = pd.read_sql(
                "SELECT * FROM reconciled_custody_events", self.conn
            )

        print(f"Loaded {len(tables)} raw tables from {self.db_path}")

    def validate_and_coerce(self) -> None:
        """Validate column types and enumerated values for each DataFrame."""
        for table, schema in REQUIRED_SCHEMA.items():
            if table in self.dfs:
                self.dfs[table] = validate_column_types(self.dfs[table], schema)
                print(f"Validated: {table} ({len(self.dfs[table])} rows)")

    def engineer_reconciliation(self) -> pd.DataFrame:
        """Run the custody reconciliation & discrepancy engine.

        Returns the reconciled_custody_events DataFrame.
        """
        if "kra_manifests" not in self.dfs or "rects_telemetry" not in self.dfs or \
           "kpc_depot_meters" not in self.dfs or "depot_lab_quality" not in self.dfs:
            raise RuntimeError("Missing required DataFrames for reconciliation.")

        m = self.dfs["kra_manifests"]
        t = self.dfs["rects_telemetry"]
        d = self.dfs["kpc_depot_meters"]
        q = self.dfs["depot_lab_quality"]

        # Inner join on consignment_id
        merged = m.merge(t, on="consignment_id", how="inner", suffixes=("_m", "_t")) \
                  .merge(d, on="consignment_id", how="inner") \
                  .merge(q, on="consignment_id", how="inner")

        if merged.empty:
            raise RuntimeError("Merge produced no rows — check consignment_id consistency.")

        # --- Volumetric Shrinkage ---
        merged["volumetric_shrinkage_pct"] = compute_volumetric_shrinkage(merged)

        # --- Density Deviation ---
        merged["density_deviation_pct"] = compute_density_deviation(merged)

        # --- Anomaly Index ---
        seal_tamper = merged["e_seal_tamper_flag"].values
        geofence = merged["geofence_status"].values
        density_dev = merged["density_deviation_pct"].values

        # Encode geofence for index: OK=0, Out-of-Corridor=1, Route-Deviation=2
        geofence_enc = np.where(geofence == "Route-Deviation", 2,
                                np.where(geofence == "Out-of-Corridor", 1, 0))

        raw = 0.4 * seal_tamper + 0.4 * geofence_enc + 0.2 * (density_dev / 20.0)  # normalize approx
        anomaly_index = np.clip(raw * 100, 0, 100).round(2)

        # Handle duplicate depot_id columns (depot_meters and depot_lab_quality both have depot_id)
        depot_id_cols = [c for c in merged.columns if c.startswith("depot_id")]
        if len(depot_id_cols) > 1:
            merged = merged.rename(columns={depot_id_cols[0]: "depot_id_std", depot_id_cols[1]: "depot_id_lab"})
            merged = merged.drop(columns="depot_id_lab")
            merged = merged.rename(columns={"depot_id_std": "depot_id"})
        elif len(depot_id_cols) == 1:
            if depot_id_cols[0] != "depot_id":
                merged = merged.rename(columns={depot_id_cols[0]: "depot_id"})

        # --- Risk Flag ---
        # Re-use simple threshold logic
        quality_flag = q["pass_quality_flag"].values if hasattr(q, "values") else np.array(q["pass_quality_flag"])
        # quality_flag alignment via merge
        quality_flag = merged["pass_quality_flag"].values

        risk = assign_risk_flag(anomaly_index, seal_tamper, density_dev, quality_flag)

        # Build output
        reconciled = pd.DataFrame(
            {
                "event_id": [f"REC_{i:06d}" for i in range(len(merged))],
                "manifest_id": merged["manifest_id"].values,
                "consignment_id": merged["consignment_id"].values,
                "depot_id": merged["depot_id"].values,
                "volumetric_shrinkage_pct": merged["volumetric_shrinkage_pct"].values,
                "density_deviation_pct": merged["density_deviation_pct"].values,
                "custody_handover_anomaly_index": anomaly_index,
                "anomaly_risk_flag": risk,
                "calculated_at": datetime.now(),
            }
        )

        self.dfs["reconciled_custody_events"] = reconciled
        print(f"Reconciliation complete: {len(reconciled)} events computed.")
        return reconciled

    def output_parquet(self, parquet_path: str = "/home/mike_mitch/Desktop/EMTech/final_capstone/data/custody_reconciled.parquet") -> None:
        """Write reconciled_custody_events to Parquet format."""
        if "reconciled_custody_events" not in self.dfs:
            raise RuntimeError("No reconciled data — run engineer_reconciliation first.")
        self.dfs["reconciled_custody_events"].to_parquet(parquet_path, index=False)
        print(f"Wrote reconciled events to: {parquet_path}")

    def output_sqlite(self, db_path: str = "/home/mike_mitch/Desktop/EMTech/final_capstone/data/custody_pipeline.db") -> None:
        """Write all validated + reconciled tables to a target SQLite database."""
        # Always create a new connection to avoid conflict with source DB connection
        conn = sqlite3.connect(db_path)

        # Write all source tables
        for table, df in self.dfs.items():
            df.to_sql(table, conn, if_exists="replace", index=False)

        # Write indexes (matching schema.sql style)
        indexes = [
            "CREATE INDEX IF NOT EXISTS idx_pipe_manifests_product ON kra_manifests (product_type)",
            "CREATE INDEX IF NOT EXISTS idx_pipe_manifests_dest ON kra_manifests (destination_type)",
            "CREATE INDEX IF NOT EXISTS idx_pipe_manifests_omc ON kra_manifests (omc)",
            "CREATE INDEX IF NOT EXISTS idx_pipe_telemetry_geofence ON rects_telemetry (geofence_status)",
            "CREATE INDEX IF NOT EXISTS idx_pipe_telemetry_tamper ON rects_telemetry (e_seal_tamper_flag)",
            "CREATE INDEX IF NOT EXISTS idx_pipe_depots_meters ON kpc_depot_meters (depot_id)",
            "CREATE INDEX IF NOT EXISTS idx_pipe_lab_quality ON depot_lab_quality (depot_id)",
            "CREATE INDEX IF NOT EXISTS idx_pipeline_events_manifest ON reconciled_custody_events (manifest_id)",
            "CREATE INDEX IF NOT EXISTS idx_pipeline_events_consignment ON reconciled_custody_events (consignment_id)",
            "CREATE INDEX IF NOT EXISTS idx_pipeline_events_risk ON reconciled_custody_events (anomaly_risk_flag)",
        ]
        for stmt in indexes:
            conn.execute(stmt)

        conn.commit()
        conn.close()
        print(f"Wrote all tables to SQLite: {db_path}")
        # self.conn = None

    def run_full_pipeline(
        self,
        parquet_path: str = "/home/mike_mitch/Desktop/EMTech/final_capstone/data/custody_reconciled.parquet",
        target_db: str = "/home/mike_mitch/Desktop/EMTech/final_capstone/data/custody_pipeline.db",
    ) -> None:
        """Execute the full pipeline: load → validate → reconcile → output."""
        self.load_raw_data()
        self.validate_and_coerce()
        self.engineer_reconciliation()
        self.output_parquet(parquet_path)
        self.output_sqlite(target_db)
        print("\nPipeline execution complete.")


# ---------------------------------------------------------------------------
# CLI entry point
# ---------------------------------------------------------------------------

def main():
    import argparse

    parser = argparse.ArgumentParser(description="HAKIKI-KPC Ingestion Pipeline")
    parser.add_argument(
        "--db", type=str, default="data/custody_data.db",
        help="Path to source SQLite from generate_custody_data.py"
    )
    parser.add_argument(
        "--parquet", type=str, default="data/custody_reconciled.parquet",
        help="Output Parquet path"
    )
    parser.add_argument(
        "--target_db", type=str, default="data/custody_pipeline.db",
        help="Target SQLite pipeline output path"
    )
    args = parser.parse_args()

    pipeline = CustodyIngestionPipeline(db_path=args.db)
    pipeline.run_full_pipeline(
        parquet_path=args.parquet,
        target_db=args.target_db,
    )


if __name__ == "__main__":
    main()